# Makefile of the ED_Tablas project
# Author: Manuel Gachs Ballegeer

# --------------------------------------------VARIABLES--------------------------------------------
# Project name
PROJECT = ed_tablas

# Compiler and compiler flags
CC = g++
FLAGS = -Wall -g

# Directories
SRCDIR = ./src
INCDIR = ./include
OBJDIR = ./obj
BINDIR = ./bin
LIBDIR = ./lib
DOCDIR = ./doc

# Files
SRC = $(wildcard *.cpp)
OBJ = $(wildcard *.o)

all:
